# Generated by Django 5.0 on 2024-11-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xscjgl', '0003_alter_exam_exam_id_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject_group',
            field=models.CharField(default='全科', max_length=10),
        ),
    ]
