# Generated by Django 5.0 on 2024-11-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xscjgl', '0005_alter_exam_exam_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_place',
            new_name='exam_platform',
        ),
    ]
