# Generated by Django 5.0 on 2024-11-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xscjgl', '0006_rename_exam_place_exam_exam_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_time',
            field=models.DateField(),
        ),
    ]
